/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as DomainRouteImport } from './routes/domain'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ServicesWebsitesRouteImport } from './routes/services.websites'
import { Route as ServicesVoipRouteImport } from './routes/services.voip'
import { Route as ServicesSocialMediaRouteImport } from './routes/services.social-media'
import { Route as ServicesMobileAppsRouteImport } from './routes/services.mobile-apps'
import { Route as ServicesMarketplaceRouteImport } from './routes/services.marketplace'
import { Route as ServicesMarketingRouteImport } from './routes/services.marketing'
import { Route as ServicesLocalListingsRouteImport } from './routes/services.local-listings'
import { Route as ServicesLeadGenerationRouteImport } from './routes/services.lead-generation'
import { Route as ServicesAiBusinessToolsRouteImport } from './routes/services.ai-business-tools'
import { Route as DashboardWebsitesRouteImport } from './routes/dashboard.websites'
import { Route as DashboardVoipRouteImport } from './routes/dashboard.voip'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSocialMediaRouteImport } from './routes/dashboard.social-media'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard.overview'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardMobileAppsRouteImport } from './routes/dashboard.mobile-apps'
import { Route as DashboardMarketplaceRouteImport } from './routes/dashboard.marketplace'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard.marketing'
import { Route as DashboardLocalListingsRouteImport } from './routes/dashboard.local-listings'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardHostingRouteImport } from './routes/dashboard.hosting'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardAiToolsRouteImport } from './routes/dashboard.ai-tools'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardAdminExceptionsRouteImport } from './routes/dashboard.admin.exceptions'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainRoute = DomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ServicesWebsitesRoute = ServicesWebsitesRouteImport.update({
  id: '/services/websites',
  path: '/services/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVoipRoute = ServicesVoipRouteImport.update({
  id: '/services/voip',
  path: '/services/voip',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocialMediaRoute = ServicesSocialMediaRouteImport.update({
  id: '/services/social-media',
  path: '/services/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileAppsRoute = ServicesMobileAppsRouteImport.update({
  id: '/services/mobile-apps',
  path: '/services/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarketplaceRoute = ServicesMarketplaceRouteImport.update({
  id: '/services/marketplace',
  path: '/services/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarketingRoute = ServicesMarketingRouteImport.update({
  id: '/services/marketing',
  path: '/services/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalListingsRoute = ServicesLocalListingsRouteImport.update({
  id: '/services/local-listings',
  path: '/services/local-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLeadGenerationRoute = ServicesLeadGenerationRouteImport.update({
  id: '/services/lead-generation',
  path: '/services/lead-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiBusinessToolsRoute = ServicesAiBusinessToolsRouteImport.update({
  id: '/services/ai-business-tools',
  path: '/services/ai-business-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebsitesRoute = DashboardWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVoipRoute = DashboardVoipRouteImport.update({
  id: '/voip',
  path: '/voip',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSocialMediaRoute = DashboardSocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMobileAppsRoute = DashboardMobileAppsRouteImport.update({
  id: '/mobile-apps',
  path: '/mobile-apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLocalListingsRoute = DashboardLocalListingsRouteImport.update({
  id: '/local-listings',
  path: '/local-listings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostingRoute = DashboardHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiToolsRoute = DashboardAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminExceptionsRoute =
  DashboardAdminExceptionsRouteImport.update({
    id: '/admin/exceptions',
    path: '/admin/exceptions',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/domain': typeof DomainRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/ai-tools': typeof DashboardAiToolsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/local-listings': typeof DashboardLocalListingsRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/mobile-apps': typeof DashboardMobileAppsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/social-media': typeof DashboardSocialMediaRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/voip': typeof DashboardVoipRoute
  '/dashboard/websites': typeof DashboardWebsitesRoute
  '/services/ai-business-tools': typeof ServicesAiBusinessToolsRoute
  '/services/lead-generation': typeof ServicesLeadGenerationRoute
  '/services/local-listings': typeof ServicesLocalListingsRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/marketplace': typeof ServicesMarketplaceRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/voip': typeof ServicesVoipRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/exceptions': typeof DashboardAdminExceptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/domain': typeof DomainRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/ai-tools': typeof DashboardAiToolsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/local-listings': typeof DashboardLocalListingsRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/mobile-apps': typeof DashboardMobileAppsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/social-media': typeof DashboardSocialMediaRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/voip': typeof DashboardVoipRoute
  '/dashboard/websites': typeof DashboardWebsitesRoute
  '/services/ai-business-tools': typeof ServicesAiBusinessToolsRoute
  '/services/lead-generation': typeof ServicesLeadGenerationRoute
  '/services/local-listings': typeof ServicesLocalListingsRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/marketplace': typeof ServicesMarketplaceRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/voip': typeof ServicesVoipRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/exceptions': typeof DashboardAdminExceptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/domain': typeof DomainRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/ai-tools': typeof DashboardAiToolsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/local-listings': typeof DashboardLocalListingsRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/mobile-apps': typeof DashboardMobileAppsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/social-media': typeof DashboardSocialMediaRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/voip': typeof DashboardVoipRoute
  '/dashboard/websites': typeof DashboardWebsitesRoute
  '/services/ai-business-tools': typeof ServicesAiBusinessToolsRoute
  '/services/lead-generation': typeof ServicesLeadGenerationRoute
  '/services/local-listings': typeof ServicesLocalListingsRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/marketplace': typeof ServicesMarketplaceRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/voip': typeof ServicesVoipRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/exceptions': typeof DashboardAdminExceptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/domain'
    | '/hosting'
    | '/login'
    | '/otp'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/ai-tools'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/invoices'
    | '/dashboard/leads'
    | '/dashboard/local-listings'
    | '/dashboard/marketing'
    | '/dashboard/marketplace'
    | '/dashboard/mobile-apps'
    | '/dashboard/orders'
    | '/dashboard/overview'
    | '/dashboard/services'
    | '/dashboard/social-media'
    | '/dashboard/support'
    | '/dashboard/voip'
    | '/dashboard/websites'
    | '/services/ai-business-tools'
    | '/services/lead-generation'
    | '/services/local-listings'
    | '/services/marketing'
    | '/services/marketplace'
    | '/services/mobile-apps'
    | '/services/social-media'
    | '/services/voip'
    | '/services/websites'
    | '/dashboard/'
    | '/dashboard/admin/exceptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/domain'
    | '/hosting'
    | '/login'
    | '/otp'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/ai-tools'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/invoices'
    | '/dashboard/leads'
    | '/dashboard/local-listings'
    | '/dashboard/marketing'
    | '/dashboard/marketplace'
    | '/dashboard/mobile-apps'
    | '/dashboard/orders'
    | '/dashboard/overview'
    | '/dashboard/services'
    | '/dashboard/social-media'
    | '/dashboard/support'
    | '/dashboard/voip'
    | '/dashboard/websites'
    | '/services/ai-business-tools'
    | '/services/lead-generation'
    | '/services/local-listings'
    | '/services/marketing'
    | '/services/marketplace'
    | '/services/mobile-apps'
    | '/services/social-media'
    | '/services/voip'
    | '/services/websites'
    | '/dashboard'
    | '/dashboard/admin/exceptions'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/domain'
    | '/hosting'
    | '/login'
    | '/otp'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/ai-tools'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/invoices'
    | '/dashboard/leads'
    | '/dashboard/local-listings'
    | '/dashboard/marketing'
    | '/dashboard/marketplace'
    | '/dashboard/mobile-apps'
    | '/dashboard/orders'
    | '/dashboard/overview'
    | '/dashboard/services'
    | '/dashboard/social-media'
    | '/dashboard/support'
    | '/dashboard/voip'
    | '/dashboard/websites'
    | '/services/ai-business-tools'
    | '/services/lead-generation'
    | '/services/local-listings'
    | '/services/marketing'
    | '/services/marketplace'
    | '/services/mobile-apps'
    | '/services/social-media'
    | '/services/voip'
    | '/services/websites'
    | '/dashboard/'
    | '/dashboard/admin/exceptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DomainRoute: typeof DomainRoute
  HostingRoute: typeof HostingRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  SignupRoute: typeof SignupRoute
  ServicesAiBusinessToolsRoute: typeof ServicesAiBusinessToolsRoute
  ServicesLeadGenerationRoute: typeof ServicesLeadGenerationRoute
  ServicesLocalListingsRoute: typeof ServicesLocalListingsRoute
  ServicesMarketingRoute: typeof ServicesMarketingRoute
  ServicesMarketplaceRoute: typeof ServicesMarketplaceRoute
  ServicesMobileAppsRoute: typeof ServicesMobileAppsRoute
  ServicesSocialMediaRoute: typeof ServicesSocialMediaRoute
  ServicesVoipRoute: typeof ServicesVoipRoute
  ServicesWebsitesRoute: typeof ServicesWebsitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain': {
      id: '/domain'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof DomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/services/websites': {
      id: '/services/websites'
      path: '/services/websites'
      fullPath: '/services/websites'
      preLoaderRoute: typeof ServicesWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/voip': {
      id: '/services/voip'
      path: '/services/voip'
      fullPath: '/services/voip'
      preLoaderRoute: typeof ServicesVoipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media': {
      id: '/services/social-media'
      path: '/services/social-media'
      fullPath: '/services/social-media'
      preLoaderRoute: typeof ServicesSocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-apps': {
      id: '/services/mobile-apps'
      path: '/services/mobile-apps'
      fullPath: '/services/mobile-apps'
      preLoaderRoute: typeof ServicesMobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marketplace': {
      id: '/services/marketplace'
      path: '/services/marketplace'
      fullPath: '/services/marketplace'
      preLoaderRoute: typeof ServicesMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marketing': {
      id: '/services/marketing'
      path: '/services/marketing'
      fullPath: '/services/marketing'
      preLoaderRoute: typeof ServicesMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-listings': {
      id: '/services/local-listings'
      path: '/services/local-listings'
      fullPath: '/services/local-listings'
      preLoaderRoute: typeof ServicesLocalListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lead-generation': {
      id: '/services/lead-generation'
      path: '/services/lead-generation'
      fullPath: '/services/lead-generation'
      preLoaderRoute: typeof ServicesLeadGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-business-tools': {
      id: '/services/ai-business-tools'
      path: '/services/ai-business-tools'
      fullPath: '/services/ai-business-tools'
      preLoaderRoute: typeof ServicesAiBusinessToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/websites': {
      id: '/dashboard/websites'
      path: '/websites'
      fullPath: '/dashboard/websites'
      preLoaderRoute: typeof DashboardWebsitesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voip': {
      id: '/dashboard/voip'
      path: '/voip'
      fullPath: '/dashboard/voip'
      preLoaderRoute: typeof DashboardVoipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/social-media': {
      id: '/dashboard/social-media'
      path: '/social-media'
      fullPath: '/dashboard/social-media'
      preLoaderRoute: typeof DashboardSocialMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mobile-apps': {
      id: '/dashboard/mobile-apps'
      path: '/mobile-apps'
      fullPath: '/dashboard/mobile-apps'
      preLoaderRoute: typeof DashboardMobileAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace': {
      id: '/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/local-listings': {
      id: '/dashboard/local-listings'
      path: '/local-listings'
      fullPath: '/dashboard/local-listings'
      preLoaderRoute: typeof DashboardLocalListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hosting': {
      id: '/dashboard/hosting'
      path: '/hosting'
      fullPath: '/dashboard/hosting'
      preLoaderRoute: typeof DashboardHostingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-tools': {
      id: '/dashboard/ai-tools'
      path: '/ai-tools'
      fullPath: '/dashboard/ai-tools'
      preLoaderRoute: typeof DashboardAiToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/exceptions': {
      id: '/dashboard/admin/exceptions'
      path: '/admin/exceptions'
      fullPath: '/dashboard/admin/exceptions'
      preLoaderRoute: typeof DashboardAdminExceptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAiToolsRoute: typeof DashboardAiToolsRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardHostingRoute: typeof DashboardHostingRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLocalListingsRoute: typeof DashboardLocalListingsRoute
  DashboardMarketingRoute: typeof DashboardMarketingRoute
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRoute
  DashboardMobileAppsRoute: typeof DashboardMobileAppsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSocialMediaRoute: typeof DashboardSocialMediaRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardVoipRoute: typeof DashboardVoipRoute
  DashboardWebsitesRoute: typeof DashboardWebsitesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminExceptionsRoute: typeof DashboardAdminExceptionsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAiToolsRoute: DashboardAiToolsRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardHostingRoute: DashboardHostingRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLocalListingsRoute: DashboardLocalListingsRoute,
  DashboardMarketingRoute: DashboardMarketingRoute,
  DashboardMarketplaceRoute: DashboardMarketplaceRoute,
  DashboardMobileAppsRoute: DashboardMobileAppsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSocialMediaRoute: DashboardSocialMediaRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardVoipRoute: DashboardVoipRoute,
  DashboardWebsitesRoute: DashboardWebsitesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminExceptionsRoute: DashboardAdminExceptionsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DomainRoute: DomainRoute,
  HostingRoute: HostingRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  SignupRoute: SignupRoute,
  ServicesAiBusinessToolsRoute: ServicesAiBusinessToolsRoute,
  ServicesLeadGenerationRoute: ServicesLeadGenerationRoute,
  ServicesLocalListingsRoute: ServicesLocalListingsRoute,
  ServicesMarketingRoute: ServicesMarketingRoute,
  ServicesMarketplaceRoute: ServicesMarketplaceRoute,
  ServicesMobileAppsRoute: ServicesMobileAppsRoute,
  ServicesSocialMediaRoute: ServicesSocialMediaRoute,
  ServicesVoipRoute: ServicesVoipRoute,
  ServicesWebsitesRoute: ServicesWebsitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
