/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as DomainRouteImport } from './routes/domain'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ServicesWebsitesRouteImport } from './routes/services.websites'
import { Route as ServicesVoipRouteImport } from './routes/services.voip'
import { Route as ServicesSocialMediaRouteImport } from './routes/services.social-media'
import { Route as ServicesMobileAppsRouteImport } from './routes/services.mobile-apps'
import { Route as ServicesMarketplaceRouteImport } from './routes/services.marketplace'
import { Route as ServicesMarketingRouteImport } from './routes/services.marketing'
import { Route as ServicesLocalListingsRouteImport } from './routes/services.local-listings'
import { Route as ServicesLeadGenerationRouteImport } from './routes/services.lead-generation'
import { Route as ServicesAiBusinessToolsRouteImport } from './routes/services.ai-business-tools'
import { Route as MarketplaceSearchRouteImport } from './routes/marketplace.search'
import { Route as MarketplacePostProjectRouteImport } from './routes/marketplace.post-project'
import { Route as DashboardWebsitesRouteImport } from './routes/dashboard.websites'
import { Route as DashboardVoipRouteImport } from './routes/dashboard.voip'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSocialMediaRouteImport } from './routes/dashboard.social-media'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard.overview'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardMobileAppsRouteImport } from './routes/dashboard.mobile-apps'
import { Route as DashboardMarketplaceRouteImport } from './routes/dashboard.marketplace'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard.marketing'
import { Route as DashboardLocalListingsRouteImport } from './routes/dashboard.local-listings'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardHostingRouteImport } from './routes/dashboard.hosting'
import { Route as DashboardFreelancerRouteImport } from './routes/dashboard.freelancer'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardAiToolsRouteImport } from './routes/dashboard.ai-tools'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardMarketplaceIndexRouteImport } from './routes/dashboard.marketplace.index'
import { Route as DashboardFreelancerIndexRouteImport } from './routes/dashboard.freelancer.index'
import { Route as MarketplaceGigsIdRouteImport } from './routes/marketplace.gigs.$id'
import { Route as MarketplaceCategorySlugRouteImport } from './routes/marketplace.category.$slug'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'
import { Route as DashboardMarketplaceProjectsRouteImport } from './routes/dashboard.marketplace.projects'
import { Route as DashboardMarketplaceMessagesRouteImport } from './routes/dashboard.marketplace.messages'
import { Route as DashboardMarketplaceDeliveriesRouteImport } from './routes/dashboard.marketplace.deliveries'
import { Route as DashboardFreelancerPayoutsRouteImport } from './routes/dashboard.freelancer.payouts'
import { Route as DashboardFreelancerDeliveriesRouteImport } from './routes/dashboard.freelancer.deliveries'
import { Route as DashboardFreelancerContractsRouteImport } from './routes/dashboard.freelancer.contracts'
import { Route as DashboardAdminProjectsRouteImport } from './routes/dashboard.admin.projects'
import { Route as DashboardAdminExceptionsRouteImport } from './routes/dashboard.admin.exceptions'
import { Route as DashboardFreelancerContractsIndexRouteImport } from './routes/dashboard.freelancer.contracts.index'
import { Route as DashboardFreelancerContractsContractIdRouteImport } from './routes/dashboard.freelancer.contracts.$contractId'
import { Route as DashboardAdminProjectsIdRouteImport } from './routes/dashboard.admin.projects.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainRoute = DomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ServicesWebsitesRoute = ServicesWebsitesRouteImport.update({
  id: '/services/websites',
  path: '/services/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVoipRoute = ServicesVoipRouteImport.update({
  id: '/services/voip',
  path: '/services/voip',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocialMediaRoute = ServicesSocialMediaRouteImport.update({
  id: '/services/social-media',
  path: '/services/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileAppsRoute = ServicesMobileAppsRouteImport.update({
  id: '/services/mobile-apps',
  path: '/services/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarketplaceRoute = ServicesMarketplaceRouteImport.update({
  id: '/services/marketplace',
  path: '/services/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarketingRoute = ServicesMarketingRouteImport.update({
  id: '/services/marketing',
  path: '/services/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalListingsRoute = ServicesLocalListingsRouteImport.update({
  id: '/services/local-listings',
  path: '/services/local-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLeadGenerationRoute = ServicesLeadGenerationRouteImport.update({
  id: '/services/lead-generation',
  path: '/services/lead-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiBusinessToolsRoute = ServicesAiBusinessToolsRouteImport.update({
  id: '/services/ai-business-tools',
  path: '/services/ai-business-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSearchRoute = MarketplaceSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplacePostProjectRoute = MarketplacePostProjectRouteImport.update({
  id: '/post-project',
  path: '/post-project',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DashboardWebsitesRoute = DashboardWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVoipRoute = DashboardVoipRouteImport.update({
  id: '/voip',
  path: '/voip',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSocialMediaRoute = DashboardSocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMobileAppsRoute = DashboardMobileAppsRouteImport.update({
  id: '/mobile-apps',
  path: '/mobile-apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLocalListingsRoute = DashboardLocalListingsRouteImport.update({
  id: '/local-listings',
  path: '/local-listings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostingRoute = DashboardHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFreelancerRoute = DashboardFreelancerRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiToolsRoute = DashboardAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceIndexRoute =
  DashboardMarketplaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMarketplaceRoute,
  } as any)
const DashboardFreelancerIndexRoute =
  DashboardFreelancerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFreelancerRoute,
  } as any)
const MarketplaceGigsIdRoute = MarketplaceGigsIdRouteImport.update({
  id: '/gigs/$id',
  path: '/gigs/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceCategorySlugRoute = MarketplaceCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMarketplaceProjectsRoute =
  DashboardMarketplaceProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => DashboardMarketplaceRoute,
  } as any)
const DashboardMarketplaceMessagesRoute =
  DashboardMarketplaceMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => DashboardMarketplaceRoute,
  } as any)
const DashboardMarketplaceDeliveriesRoute =
  DashboardMarketplaceDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => DashboardMarketplaceRoute,
  } as any)
const DashboardFreelancerPayoutsRoute =
  DashboardFreelancerPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => DashboardFreelancerRoute,
  } as any)
const DashboardFreelancerDeliveriesRoute =
  DashboardFreelancerDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => DashboardFreelancerRoute,
  } as any)
const DashboardFreelancerContractsRoute =
  DashboardFreelancerContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => DashboardFreelancerRoute,
  } as any)
const DashboardAdminProjectsRoute = DashboardAdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminExceptionsRoute =
  DashboardAdminExceptionsRouteImport.update({
    id: '/admin/exceptions',
    path: '/admin/exceptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFreelancerContractsIndexRoute =
  DashboardFreelancerContractsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFreelancerContractsRoute,
  } as any)
const DashboardFreelancerContractsContractIdRoute =
  DashboardFreelancerContractsContractIdRouteImport.update({
    id: '/$contractId',
    path: '/$contractId',
    getParentRoute: () => DashboardFreelancerContractsRoute,
  } as any)
const DashboardAdminProjectsIdRoute =
  DashboardAdminProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardAdminProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deals': typeof DealsRoute
  '/domain': typeof DomainRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/otp': typeof OtpRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/ai-tools': typeof DashboardAiToolsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRouteWithChildren
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/local-listings': typeof DashboardLocalListingsRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRouteWithChildren
  '/dashboard/mobile-apps': typeof DashboardMobileAppsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/social-media': typeof DashboardSocialMediaRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/voip': typeof DashboardVoipRoute
  '/dashboard/websites': typeof DashboardWebsitesRoute
  '/marketplace/post-project': typeof MarketplacePostProjectRoute
  '/marketplace/search': typeof MarketplaceSearchRoute
  '/services/ai-business-tools': typeof ServicesAiBusinessToolsRoute
  '/services/lead-generation': typeof ServicesLeadGenerationRoute
  '/services/local-listings': typeof ServicesLocalListingsRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/marketplace': typeof ServicesMarketplaceRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/voip': typeof ServicesVoipRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/dashboard/admin/exceptions': typeof DashboardAdminExceptionsRoute
  '/dashboard/admin/projects': typeof DashboardAdminProjectsRouteWithChildren
  '/dashboard/freelancer/contracts': typeof DashboardFreelancerContractsRouteWithChildren
  '/dashboard/freelancer/deliveries': typeof DashboardFreelancerDeliveriesRoute
  '/dashboard/freelancer/payouts': typeof DashboardFreelancerPayoutsRoute
  '/dashboard/marketplace/deliveries': typeof DashboardMarketplaceDeliveriesRoute
  '/dashboard/marketplace/messages': typeof DashboardMarketplaceMessagesRoute
  '/dashboard/marketplace/projects': typeof DashboardMarketplaceProjectsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/marketplace/category/$slug': typeof MarketplaceCategorySlugRoute
  '/marketplace/gigs/$id': typeof MarketplaceGigsIdRoute
  '/dashboard/freelancer/': typeof DashboardFreelancerIndexRoute
  '/dashboard/marketplace/': typeof DashboardMarketplaceIndexRoute
  '/dashboard/admin/projects/$id': typeof DashboardAdminProjectsIdRoute
  '/dashboard/freelancer/contracts/$contractId': typeof DashboardFreelancerContractsContractIdRoute
  '/dashboard/freelancer/contracts/': typeof DashboardFreelancerContractsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/deals': typeof DealsRoute
  '/domain': typeof DomainRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/ai-tools': typeof DashboardAiToolsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/local-listings': typeof DashboardLocalListingsRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/mobile-apps': typeof DashboardMobileAppsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/social-media': typeof DashboardSocialMediaRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/voip': typeof DashboardVoipRoute
  '/dashboard/websites': typeof DashboardWebsitesRoute
  '/marketplace/post-project': typeof MarketplacePostProjectRoute
  '/marketplace/search': typeof MarketplaceSearchRoute
  '/services/ai-business-tools': typeof ServicesAiBusinessToolsRoute
  '/services/lead-generation': typeof ServicesLeadGenerationRoute
  '/services/local-listings': typeof ServicesLocalListingsRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/marketplace': typeof ServicesMarketplaceRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/voip': typeof ServicesVoipRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/dashboard/admin/exceptions': typeof DashboardAdminExceptionsRoute
  '/dashboard/admin/projects': typeof DashboardAdminProjectsRouteWithChildren
  '/dashboard/freelancer/deliveries': typeof DashboardFreelancerDeliveriesRoute
  '/dashboard/freelancer/payouts': typeof DashboardFreelancerPayoutsRoute
  '/dashboard/marketplace/deliveries': typeof DashboardMarketplaceDeliveriesRoute
  '/dashboard/marketplace/messages': typeof DashboardMarketplaceMessagesRoute
  '/dashboard/marketplace/projects': typeof DashboardMarketplaceProjectsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/marketplace/category/$slug': typeof MarketplaceCategorySlugRoute
  '/marketplace/gigs/$id': typeof MarketplaceGigsIdRoute
  '/dashboard/freelancer': typeof DashboardFreelancerIndexRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceIndexRoute
  '/dashboard/admin/projects/$id': typeof DashboardAdminProjectsIdRoute
  '/dashboard/freelancer/contracts/$contractId': typeof DashboardFreelancerContractsContractIdRoute
  '/dashboard/freelancer/contracts': typeof DashboardFreelancerContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deals': typeof DealsRoute
  '/domain': typeof DomainRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/otp': typeof OtpRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/ai-tools': typeof DashboardAiToolsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRouteWithChildren
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/local-listings': typeof DashboardLocalListingsRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRouteWithChildren
  '/dashboard/mobile-apps': typeof DashboardMobileAppsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/social-media': typeof DashboardSocialMediaRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/voip': typeof DashboardVoipRoute
  '/dashboard/websites': typeof DashboardWebsitesRoute
  '/marketplace/post-project': typeof MarketplacePostProjectRoute
  '/marketplace/search': typeof MarketplaceSearchRoute
  '/services/ai-business-tools': typeof ServicesAiBusinessToolsRoute
  '/services/lead-generation': typeof ServicesLeadGenerationRoute
  '/services/local-listings': typeof ServicesLocalListingsRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/marketplace': typeof ServicesMarketplaceRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/voip': typeof ServicesVoipRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/dashboard/admin/exceptions': typeof DashboardAdminExceptionsRoute
  '/dashboard/admin/projects': typeof DashboardAdminProjectsRouteWithChildren
  '/dashboard/freelancer/contracts': typeof DashboardFreelancerContractsRouteWithChildren
  '/dashboard/freelancer/deliveries': typeof DashboardFreelancerDeliveriesRoute
  '/dashboard/freelancer/payouts': typeof DashboardFreelancerPayoutsRoute
  '/dashboard/marketplace/deliveries': typeof DashboardMarketplaceDeliveriesRoute
  '/dashboard/marketplace/messages': typeof DashboardMarketplaceMessagesRoute
  '/dashboard/marketplace/projects': typeof DashboardMarketplaceProjectsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/marketplace/category/$slug': typeof MarketplaceCategorySlugRoute
  '/marketplace/gigs/$id': typeof MarketplaceGigsIdRoute
  '/dashboard/freelancer/': typeof DashboardFreelancerIndexRoute
  '/dashboard/marketplace/': typeof DashboardMarketplaceIndexRoute
  '/dashboard/admin/projects/$id': typeof DashboardAdminProjectsIdRoute
  '/dashboard/freelancer/contracts/$contractId': typeof DashboardFreelancerContractsContractIdRoute
  '/dashboard/freelancer/contracts/': typeof DashboardFreelancerContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/deals'
    | '/domain'
    | '/hosting'
    | '/login'
    | '/marketplace'
    | '/otp'
    | '/search'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/ai-tools'
    | '/dashboard/domains'
    | '/dashboard/freelancer'
    | '/dashboard/hosting'
    | '/dashboard/invoices'
    | '/dashboard/leads'
    | '/dashboard/local-listings'
    | '/dashboard/marketing'
    | '/dashboard/marketplace'
    | '/dashboard/mobile-apps'
    | '/dashboard/orders'
    | '/dashboard/overview'
    | '/dashboard/services'
    | '/dashboard/social-media'
    | '/dashboard/support'
    | '/dashboard/voip'
    | '/dashboard/websites'
    | '/marketplace/post-project'
    | '/marketplace/search'
    | '/services/ai-business-tools'
    | '/services/lead-generation'
    | '/services/local-listings'
    | '/services/marketing'
    | '/services/marketplace'
    | '/services/mobile-apps'
    | '/services/social-media'
    | '/services/voip'
    | '/services/websites'
    | '/dashboard/'
    | '/marketplace/'
    | '/dashboard/admin/exceptions'
    | '/dashboard/admin/projects'
    | '/dashboard/freelancer/contracts'
    | '/dashboard/freelancer/deliveries'
    | '/dashboard/freelancer/payouts'
    | '/dashboard/marketplace/deliveries'
    | '/dashboard/marketplace/messages'
    | '/dashboard/marketplace/projects'
    | '/dashboard/projects/$projectId'
    | '/marketplace/category/$slug'
    | '/marketplace/gigs/$id'
    | '/dashboard/freelancer/'
    | '/dashboard/marketplace/'
    | '/dashboard/admin/projects/$id'
    | '/dashboard/freelancer/contracts/$contractId'
    | '/dashboard/freelancer/contracts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/deals'
    | '/domain'
    | '/hosting'
    | '/login'
    | '/otp'
    | '/search'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/ai-tools'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/invoices'
    | '/dashboard/leads'
    | '/dashboard/local-listings'
    | '/dashboard/marketing'
    | '/dashboard/mobile-apps'
    | '/dashboard/orders'
    | '/dashboard/overview'
    | '/dashboard/services'
    | '/dashboard/social-media'
    | '/dashboard/support'
    | '/dashboard/voip'
    | '/dashboard/websites'
    | '/marketplace/post-project'
    | '/marketplace/search'
    | '/services/ai-business-tools'
    | '/services/lead-generation'
    | '/services/local-listings'
    | '/services/marketing'
    | '/services/marketplace'
    | '/services/mobile-apps'
    | '/services/social-media'
    | '/services/voip'
    | '/services/websites'
    | '/dashboard'
    | '/marketplace'
    | '/dashboard/admin/exceptions'
    | '/dashboard/admin/projects'
    | '/dashboard/freelancer/deliveries'
    | '/dashboard/freelancer/payouts'
    | '/dashboard/marketplace/deliveries'
    | '/dashboard/marketplace/messages'
    | '/dashboard/marketplace/projects'
    | '/dashboard/projects/$projectId'
    | '/marketplace/category/$slug'
    | '/marketplace/gigs/$id'
    | '/dashboard/freelancer'
    | '/dashboard/marketplace'
    | '/dashboard/admin/projects/$id'
    | '/dashboard/freelancer/contracts/$contractId'
    | '/dashboard/freelancer/contracts'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/deals'
    | '/domain'
    | '/hosting'
    | '/login'
    | '/marketplace'
    | '/otp'
    | '/search'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/ai-tools'
    | '/dashboard/domains'
    | '/dashboard/freelancer'
    | '/dashboard/hosting'
    | '/dashboard/invoices'
    | '/dashboard/leads'
    | '/dashboard/local-listings'
    | '/dashboard/marketing'
    | '/dashboard/marketplace'
    | '/dashboard/mobile-apps'
    | '/dashboard/orders'
    | '/dashboard/overview'
    | '/dashboard/services'
    | '/dashboard/social-media'
    | '/dashboard/support'
    | '/dashboard/voip'
    | '/dashboard/websites'
    | '/marketplace/post-project'
    | '/marketplace/search'
    | '/services/ai-business-tools'
    | '/services/lead-generation'
    | '/services/local-listings'
    | '/services/marketing'
    | '/services/marketplace'
    | '/services/mobile-apps'
    | '/services/social-media'
    | '/services/voip'
    | '/services/websites'
    | '/dashboard/'
    | '/marketplace/'
    | '/dashboard/admin/exceptions'
    | '/dashboard/admin/projects'
    | '/dashboard/freelancer/contracts'
    | '/dashboard/freelancer/deliveries'
    | '/dashboard/freelancer/payouts'
    | '/dashboard/marketplace/deliveries'
    | '/dashboard/marketplace/messages'
    | '/dashboard/marketplace/projects'
    | '/dashboard/projects/$projectId'
    | '/marketplace/category/$slug'
    | '/marketplace/gigs/$id'
    | '/dashboard/freelancer/'
    | '/dashboard/marketplace/'
    | '/dashboard/admin/projects/$id'
    | '/dashboard/freelancer/contracts/$contractId'
    | '/dashboard/freelancer/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DealsRoute: typeof DealsRoute
  DomainRoute: typeof DomainRoute
  HostingRoute: typeof HostingRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  OtpRoute: typeof OtpRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  ServicesAiBusinessToolsRoute: typeof ServicesAiBusinessToolsRoute
  ServicesLeadGenerationRoute: typeof ServicesLeadGenerationRoute
  ServicesLocalListingsRoute: typeof ServicesLocalListingsRoute
  ServicesMarketingRoute: typeof ServicesMarketingRoute
  ServicesMarketplaceRoute: typeof ServicesMarketplaceRoute
  ServicesMobileAppsRoute: typeof ServicesMobileAppsRoute
  ServicesSocialMediaRoute: typeof ServicesSocialMediaRoute
  ServicesVoipRoute: typeof ServicesVoipRoute
  ServicesWebsitesRoute: typeof ServicesWebsitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain': {
      id: '/domain'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof DomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/services/websites': {
      id: '/services/websites'
      path: '/services/websites'
      fullPath: '/services/websites'
      preLoaderRoute: typeof ServicesWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/voip': {
      id: '/services/voip'
      path: '/services/voip'
      fullPath: '/services/voip'
      preLoaderRoute: typeof ServicesVoipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media': {
      id: '/services/social-media'
      path: '/services/social-media'
      fullPath: '/services/social-media'
      preLoaderRoute: typeof ServicesSocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-apps': {
      id: '/services/mobile-apps'
      path: '/services/mobile-apps'
      fullPath: '/services/mobile-apps'
      preLoaderRoute: typeof ServicesMobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marketplace': {
      id: '/services/marketplace'
      path: '/services/marketplace'
      fullPath: '/services/marketplace'
      preLoaderRoute: typeof ServicesMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marketing': {
      id: '/services/marketing'
      path: '/services/marketing'
      fullPath: '/services/marketing'
      preLoaderRoute: typeof ServicesMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-listings': {
      id: '/services/local-listings'
      path: '/services/local-listings'
      fullPath: '/services/local-listings'
      preLoaderRoute: typeof ServicesLocalListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lead-generation': {
      id: '/services/lead-generation'
      path: '/services/lead-generation'
      fullPath: '/services/lead-generation'
      preLoaderRoute: typeof ServicesLeadGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-business-tools': {
      id: '/services/ai-business-tools'
      path: '/services/ai-business-tools'
      fullPath: '/services/ai-business-tools'
      preLoaderRoute: typeof ServicesAiBusinessToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/search': {
      id: '/marketplace/search'
      path: '/search'
      fullPath: '/marketplace/search'
      preLoaderRoute: typeof MarketplaceSearchRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/post-project': {
      id: '/marketplace/post-project'
      path: '/post-project'
      fullPath: '/marketplace/post-project'
      preLoaderRoute: typeof MarketplacePostProjectRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/dashboard/websites': {
      id: '/dashboard/websites'
      path: '/websites'
      fullPath: '/dashboard/websites'
      preLoaderRoute: typeof DashboardWebsitesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voip': {
      id: '/dashboard/voip'
      path: '/voip'
      fullPath: '/dashboard/voip'
      preLoaderRoute: typeof DashboardVoipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/social-media': {
      id: '/dashboard/social-media'
      path: '/social-media'
      fullPath: '/dashboard/social-media'
      preLoaderRoute: typeof DashboardSocialMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mobile-apps': {
      id: '/dashboard/mobile-apps'
      path: '/mobile-apps'
      fullPath: '/dashboard/mobile-apps'
      preLoaderRoute: typeof DashboardMobileAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace': {
      id: '/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/local-listings': {
      id: '/dashboard/local-listings'
      path: '/local-listings'
      fullPath: '/dashboard/local-listings'
      preLoaderRoute: typeof DashboardLocalListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hosting': {
      id: '/dashboard/hosting'
      path: '/hosting'
      fullPath: '/dashboard/hosting'
      preLoaderRoute: typeof DashboardHostingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/freelancer': {
      id: '/dashboard/freelancer'
      path: '/freelancer'
      fullPath: '/dashboard/freelancer'
      preLoaderRoute: typeof DashboardFreelancerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-tools': {
      id: '/dashboard/ai-tools'
      path: '/ai-tools'
      fullPath: '/dashboard/ai-tools'
      preLoaderRoute: typeof DashboardAiToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace/': {
      id: '/dashboard/marketplace/'
      path: '/'
      fullPath: '/dashboard/marketplace/'
      preLoaderRoute: typeof DashboardMarketplaceIndexRouteImport
      parentRoute: typeof DashboardMarketplaceRoute
    }
    '/dashboard/freelancer/': {
      id: '/dashboard/freelancer/'
      path: '/'
      fullPath: '/dashboard/freelancer/'
      preLoaderRoute: typeof DashboardFreelancerIndexRouteImport
      parentRoute: typeof DashboardFreelancerRoute
    }
    '/marketplace/gigs/$id': {
      id: '/marketplace/gigs/$id'
      path: '/gigs/$id'
      fullPath: '/marketplace/gigs/$id'
      preLoaderRoute: typeof MarketplaceGigsIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/category/$slug': {
      id: '/marketplace/category/$slug'
      path: '/category/$slug'
      fullPath: '/marketplace/category/$slug'
      preLoaderRoute: typeof MarketplaceCategorySlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace/projects': {
      id: '/dashboard/marketplace/projects'
      path: '/projects'
      fullPath: '/dashboard/marketplace/projects'
      preLoaderRoute: typeof DashboardMarketplaceProjectsRouteImport
      parentRoute: typeof DashboardMarketplaceRoute
    }
    '/dashboard/marketplace/messages': {
      id: '/dashboard/marketplace/messages'
      path: '/messages'
      fullPath: '/dashboard/marketplace/messages'
      preLoaderRoute: typeof DashboardMarketplaceMessagesRouteImport
      parentRoute: typeof DashboardMarketplaceRoute
    }
    '/dashboard/marketplace/deliveries': {
      id: '/dashboard/marketplace/deliveries'
      path: '/deliveries'
      fullPath: '/dashboard/marketplace/deliveries'
      preLoaderRoute: typeof DashboardMarketplaceDeliveriesRouteImport
      parentRoute: typeof DashboardMarketplaceRoute
    }
    '/dashboard/freelancer/payouts': {
      id: '/dashboard/freelancer/payouts'
      path: '/payouts'
      fullPath: '/dashboard/freelancer/payouts'
      preLoaderRoute: typeof DashboardFreelancerPayoutsRouteImport
      parentRoute: typeof DashboardFreelancerRoute
    }
    '/dashboard/freelancer/deliveries': {
      id: '/dashboard/freelancer/deliveries'
      path: '/deliveries'
      fullPath: '/dashboard/freelancer/deliveries'
      preLoaderRoute: typeof DashboardFreelancerDeliveriesRouteImport
      parentRoute: typeof DashboardFreelancerRoute
    }
    '/dashboard/freelancer/contracts': {
      id: '/dashboard/freelancer/contracts'
      path: '/contracts'
      fullPath: '/dashboard/freelancer/contracts'
      preLoaderRoute: typeof DashboardFreelancerContractsRouteImport
      parentRoute: typeof DashboardFreelancerRoute
    }
    '/dashboard/admin/projects': {
      id: '/dashboard/admin/projects'
      path: '/admin/projects'
      fullPath: '/dashboard/admin/projects'
      preLoaderRoute: typeof DashboardAdminProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/exceptions': {
      id: '/dashboard/admin/exceptions'
      path: '/admin/exceptions'
      fullPath: '/dashboard/admin/exceptions'
      preLoaderRoute: typeof DashboardAdminExceptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/freelancer/contracts/': {
      id: '/dashboard/freelancer/contracts/'
      path: '/'
      fullPath: '/dashboard/freelancer/contracts/'
      preLoaderRoute: typeof DashboardFreelancerContractsIndexRouteImport
      parentRoute: typeof DashboardFreelancerContractsRoute
    }
    '/dashboard/freelancer/contracts/$contractId': {
      id: '/dashboard/freelancer/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/dashboard/freelancer/contracts/$contractId'
      preLoaderRoute: typeof DashboardFreelancerContractsContractIdRouteImport
      parentRoute: typeof DashboardFreelancerContractsRoute
    }
    '/dashboard/admin/projects/$id': {
      id: '/dashboard/admin/projects/$id'
      path: '/$id'
      fullPath: '/dashboard/admin/projects/$id'
      preLoaderRoute: typeof DashboardAdminProjectsIdRouteImport
      parentRoute: typeof DashboardAdminProjectsRoute
    }
  }
}

interface DashboardFreelancerContractsRouteChildren {
  DashboardFreelancerContractsContractIdRoute: typeof DashboardFreelancerContractsContractIdRoute
  DashboardFreelancerContractsIndexRoute: typeof DashboardFreelancerContractsIndexRoute
}

const DashboardFreelancerContractsRouteChildren: DashboardFreelancerContractsRouteChildren =
  {
    DashboardFreelancerContractsContractIdRoute:
      DashboardFreelancerContractsContractIdRoute,
    DashboardFreelancerContractsIndexRoute:
      DashboardFreelancerContractsIndexRoute,
  }

const DashboardFreelancerContractsRouteWithChildren =
  DashboardFreelancerContractsRoute._addFileChildren(
    DashboardFreelancerContractsRouteChildren,
  )

interface DashboardFreelancerRouteChildren {
  DashboardFreelancerContractsRoute: typeof DashboardFreelancerContractsRouteWithChildren
  DashboardFreelancerDeliveriesRoute: typeof DashboardFreelancerDeliveriesRoute
  DashboardFreelancerPayoutsRoute: typeof DashboardFreelancerPayoutsRoute
  DashboardFreelancerIndexRoute: typeof DashboardFreelancerIndexRoute
}

const DashboardFreelancerRouteChildren: DashboardFreelancerRouteChildren = {
  DashboardFreelancerContractsRoute:
    DashboardFreelancerContractsRouteWithChildren,
  DashboardFreelancerDeliveriesRoute: DashboardFreelancerDeliveriesRoute,
  DashboardFreelancerPayoutsRoute: DashboardFreelancerPayoutsRoute,
  DashboardFreelancerIndexRoute: DashboardFreelancerIndexRoute,
}

const DashboardFreelancerRouteWithChildren =
  DashboardFreelancerRoute._addFileChildren(DashboardFreelancerRouteChildren)

interface DashboardMarketplaceRouteChildren {
  DashboardMarketplaceDeliveriesRoute: typeof DashboardMarketplaceDeliveriesRoute
  DashboardMarketplaceMessagesRoute: typeof DashboardMarketplaceMessagesRoute
  DashboardMarketplaceProjectsRoute: typeof DashboardMarketplaceProjectsRoute
  DashboardMarketplaceIndexRoute: typeof DashboardMarketplaceIndexRoute
}

const DashboardMarketplaceRouteChildren: DashboardMarketplaceRouteChildren = {
  DashboardMarketplaceDeliveriesRoute: DashboardMarketplaceDeliveriesRoute,
  DashboardMarketplaceMessagesRoute: DashboardMarketplaceMessagesRoute,
  DashboardMarketplaceProjectsRoute: DashboardMarketplaceProjectsRoute,
  DashboardMarketplaceIndexRoute: DashboardMarketplaceIndexRoute,
}

const DashboardMarketplaceRouteWithChildren =
  DashboardMarketplaceRoute._addFileChildren(DashboardMarketplaceRouteChildren)

interface DashboardAdminProjectsRouteChildren {
  DashboardAdminProjectsIdRoute: typeof DashboardAdminProjectsIdRoute
}

const DashboardAdminProjectsRouteChildren: DashboardAdminProjectsRouteChildren =
  {
    DashboardAdminProjectsIdRoute: DashboardAdminProjectsIdRoute,
  }

const DashboardAdminProjectsRouteWithChildren =
  DashboardAdminProjectsRoute._addFileChildren(
    DashboardAdminProjectsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAiToolsRoute: typeof DashboardAiToolsRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardFreelancerRoute: typeof DashboardFreelancerRouteWithChildren
  DashboardHostingRoute: typeof DashboardHostingRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLocalListingsRoute: typeof DashboardLocalListingsRoute
  DashboardMarketingRoute: typeof DashboardMarketingRoute
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRouteWithChildren
  DashboardMobileAppsRoute: typeof DashboardMobileAppsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSocialMediaRoute: typeof DashboardSocialMediaRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardVoipRoute: typeof DashboardVoipRoute
  DashboardWebsitesRoute: typeof DashboardWebsitesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminExceptionsRoute: typeof DashboardAdminExceptionsRoute
  DashboardAdminProjectsRoute: typeof DashboardAdminProjectsRouteWithChildren
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAiToolsRoute: DashboardAiToolsRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardFreelancerRoute: DashboardFreelancerRouteWithChildren,
  DashboardHostingRoute: DashboardHostingRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLocalListingsRoute: DashboardLocalListingsRoute,
  DashboardMarketingRoute: DashboardMarketingRoute,
  DashboardMarketplaceRoute: DashboardMarketplaceRouteWithChildren,
  DashboardMobileAppsRoute: DashboardMobileAppsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSocialMediaRoute: DashboardSocialMediaRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardVoipRoute: DashboardVoipRoute,
  DashboardWebsitesRoute: DashboardWebsitesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminExceptionsRoute: DashboardAdminExceptionsRoute,
  DashboardAdminProjectsRoute: DashboardAdminProjectsRouteWithChildren,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplacePostProjectRoute: typeof MarketplacePostProjectRoute
  MarketplaceSearchRoute: typeof MarketplaceSearchRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceCategorySlugRoute: typeof MarketplaceCategorySlugRoute
  MarketplaceGigsIdRoute: typeof MarketplaceGigsIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplacePostProjectRoute: MarketplacePostProjectRoute,
  MarketplaceSearchRoute: MarketplaceSearchRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceCategorySlugRoute: MarketplaceCategorySlugRoute,
  MarketplaceGigsIdRoute: MarketplaceGigsIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DealsRoute: DealsRoute,
  DomainRoute: DomainRoute,
  HostingRoute: HostingRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  OtpRoute: OtpRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  ServicesAiBusinessToolsRoute: ServicesAiBusinessToolsRoute,
  ServicesLeadGenerationRoute: ServicesLeadGenerationRoute,
  ServicesLocalListingsRoute: ServicesLocalListingsRoute,
  ServicesMarketingRoute: ServicesMarketingRoute,
  ServicesMarketplaceRoute: ServicesMarketplaceRoute,
  ServicesMobileAppsRoute: ServicesMobileAppsRoute,
  ServicesSocialMediaRoute: ServicesSocialMediaRoute,
  ServicesVoipRoute: ServicesVoipRoute,
  ServicesWebsitesRoute: ServicesWebsitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
